apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-frontend
  name: deployment-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-frontend
    spec:
      containers:
      - image: gorm2303/simple-fortune-cookie-frontend:latest
        name: frontend
        resources: {}
status: {}